services:
    victoire_page.user_callable:
        class: Victoire\Bundle\PageBundle\Helper\UserCallableHelper
        arguments:
            - "@service_container"

    page.subscriber:
        class: Victoire\Bundle\PageBundle\EventSubscriber\PageSubscriber
        arguments:
            - "@router.default"
            - "@victoire_page.user_callable"
            - "%victoire_core.user_class%"
            - "@victoire_view_reference.builder"
            - "@victoire_view_reference.repository"
            - "@victoire_api_business_entity.resolver.api_business_entity_resolver"
        tags:
            - { name: doctrine.event_subscriber, connection: default, priority: -11 }

    victoire_page.page_helper:
        class: Victoire\Bundle\PageBundle\Helper\PageHelper
        arguments:
            - "@victoire_core.helper.business_entity_helper"
            - "@doctrine.orm.entity_manager"
            - "@victoire_view_reference.helper"
            - "@victoire_core.current_view"
            - "@event_dispatcher"
            - "@service_container"
            - "@victoire_seo.helper.pageseo_helper"
            - "@session"
            - "@security.token_storage"
            - "@security.authorization_checker"
            - "@victoire_widget_map.builder"
            - "@victoire_business_page.business_page_builder"
            - "@victoire_business_page.business_page_helper"
            - "@victoire_widget_map.widget_data_warmer"
            - "@victoire_view_reference.repository"
            - "@victoire_api_business_entity.resolver.api_business_entity_resolver"

    ####################################################################################################################
    # Security voter
    ####################################################################################################################
    page.security.voter.page_owner:
        class: Victoire\Bundle\PageBundle\Security\Voter\PageOwnerVoter
        arguments: ['%victoire_core.user_class%']
        tags:
            - { name: security.voter }

    page.security.voter.page_debug:
        class: Victoire\Bundle\PageBundle\Security\Voter\PageDebugVoter
        arguments: ['%victoire_core.user_class%']
        tags:
            - { name: security.voter }
    ####################################################################################################################
    # Forms
    ####################################################################################################################

    victoire_page.page.form.type:
        parent: victoire_core.view.form.type
        class: Victoire\Bundle\PageBundle\Form\PageType
        tags:
            - { name: form.type }

    victoire_page.page_settings.form.type:
        parent: "victoire_core.view.form.type"
        class: Victoire\Bundle\PageBundle\Form\PageSettingsType
        tags:
            - { name: form.type }


    ####################################################################################################################
    # Menu
    ####################################################################################################################

    victoire_core.page_menu_listener:
        class: Victoire\Bundle\PageBundle\Listener\PageMenuListener
        arguments: ["@victoire_core.admin_menu_builder"]
        tags:
            - { name: kernel.event_listener, event: victoire_core.build_menu, method: addGlobal, priority: 100 }

    victoire_core.page_menu.contextual:
        class: Victoire\Bundle\PageBundle\Listener\PageMenuListener
        arguments: ["@victoire_core.admin_menu_builder"]
        tags:
            - { name: kernel.event_listener, event: victoire_core.page_menu.contextual, method: addContextual }

    ####################################################################################################################
    # twig
    ####################################################################################################################

    victoire_page.twig.page_extension:
        class: Victoire\Bundle\PageBundle\Twig\Extension\PageExtension
        arguments:
            - "@victoire_business_page.business_page_helper"
            - "@router"
            - "@victoire_page.page_helper"
            - "@victoire_core.current_view"
            - "@victoire_core.view_css_builder"
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: twig.extension }

    ####################################################################################################################
    # ViewReference
    ####################################################################################################################

    victoire_page.page_reference_builder:
        class: Victoire\Bundle\PageBundle\Builder\PageReferenceBuilder
        parent: victoire_view_reference.base_view_reference.builder
        tags:
            - { name: victoire_view_reference.view_reference.builder, view: Victoire\Bundle\PageBundle\Entity\Page }
