@mink:selenium2 @alice(Page) @reset-schema
Feature: Create a blog

Background:
    Given I maximize the window
    And I am on homepage

    Scenario: I create a new blog
        Then I should see "Blog"
        When I follow "Blog"
        Then I should see "No result"
        When I follow "Create a new blog"
        Then I should see "Permissions needed to display the page"
        When I fill in "blog[translations][en][name]" with "The Jedi network"
        And I follow "Create"
        Then I should see "Successfully created page"
        And the title should be "The Jedi network"
        When I switch to "layout" mode
        Then I should see "New content"
        When I select "Force" from the "1" select of "main_content" slot
        Then I should see "Force side"
        When I fill in "Force side" with "dark"
        And I submit the widget
        Then I should see "The dark side of the force"

    @alice(Blog) @alice(BlogTemplate)
    Scenario: I create a new article
        Then I should see "Blog"
        When I follow "Blog"
        Then I should see "The Jedi Network"
        And I should see "Create a post now"
        When I follow "Create a post now"
        Then I should see "Create a new post"
        And I should see "If this field is empty, the slug will be autogenerated"
        When I fill in "article_translations_en_name" with "I'm your father."
        And I fill in "article_translations_en_description" with "This is a great description."
        And I select "First blog template" from "Template"
        And I follow "Create"
        And I wait 5 seconds
        Then I should be on "/en/the-jedi-network/i-m-your-father"

    @alice(Blog) @alice(BlogTemplate)
    Scenario: I create a new article with a slug
        Then I should see "Blog"
        When I follow "Blog"
        Then I should see "The Jedi Network"
        And I should see "Create a post now"
        When I follow "Create a post now"
        Then I should see "Create a new post"
        And I should see "If this field is empty, the slug will be autogenerated"
        When I fill in "article_translations_en_name" with "I'm your father."
        When I fill in "article_translations_en_description" with "This is a great description."
        When I fill in "article_translations_en_slug" with "custom-slug"
        When I select "First blog template" from "Template"
        And I follow "Create"
        And I wait 5 seconds
        Then I should be on "/en/the-jedi-network/custom-slug"

    @alice(Blog) @alice(Article) @alice(BlogTemplate)
    Scenario: I can view the Article list in the blog management window
        Then I should see "Blog"
        When I follow "Blog"
        Then I should see "Posts lists"
        And I should see "I'm your father."
        And I should see "Anakin Skywalker"
