version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.1-fpm-node-browsers
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - restore_cache:
          keys:
          - composer-v1-{{ .Branch }}
          # fallback to using the latest cache if no exact match is found
          - composer-v1-
      - run: bash victoire-test-suite/dependencies.sh victoire/victoire
      - run: mkdir -p ~/phpunit
      - run: php ./vendor/bin/phpunit
      - run: bash victoire-test-suite/circle.sh victoire/victoire
      - store_test_results:
          path: ~/phpunit
      - store_artifacts:
          path: fails
      - save_cache:
          key: composer-v1-{{ .Branch }}
          paths:
              - ~/.composer/cache
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test1:
          requires:
            - build
      - test2:
          requires:
            - build
      - test3:
          requires:
            - build
      - test4:
          requires:
            - build