services:
    ####################################################################################################################
    # Forms
    ####################################################################################################################

    victoire_template.template.form.type:
        parent: "victoire_core.view.form.type"
        class: Victoire\Bundle\TemplateBundle\Form\TemplateType
        tags:
            - { name: form.type }
        calls:
            - [ setLayouts, ["%victoire_core.layouts%"] ]

    ####################################################################################################################
    # Menu
    ####################################################################################################################

    victoire_core.template_menu_listener:
        class: Victoire\Bundle\TemplateBundle\Listener\TemplateMenuListener
        arguments: ["@victoire_core.admin_menu_builder"]
        tags:
            - { name: kernel.event_listener, event: victoire_core.build_menu, method: addGlobal, priority: 80 }

    victoire_core.template_menu.contextual:
        class: Victoire\Bundle\TemplateBundle\Listener\TemplateMenuListener
        arguments: ["@victoire_core.admin_menu_builder"]
        tags:
            - { name: kernel.event_listener, event: victoire_core.template_menu.contextual, method: addContextual }
