<?php
namespace Victoire\Bundle\MediaBundle\Tests\Entity;

use Victoire\Bundle\MediaBundle\Entity\Folder;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-28 at 14:19:20.
 */
class FolderTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Folder
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Folder;
    }

    /**
     * @covers Victoire\Bundle\MediaBundle\Entity\Folder::getName
     * @covers Victoire\Bundle\MediaBundle\Entity\Folder::setName
     */
    public function testGetSetName()
    {
        $this->object->setName('abc');
        $this->assertEquals('abc', $this->object->getName());
    }

    /**
     * @covers Victoire\Bundle\MediaBundle\Entity\Folder::getRel
     * @covers Victoire\Bundle\MediaBundle\Entity\Folder::setRel
     */
    public function testGetSetRel()
    {
        $this->object->setRel('bcd');
        $this->assertEquals('bcd', $this->object->getRel());
    }

    /**
     * @covers Victoire\Bundle\MediaBundle\Entity\Folder::getCreatedAt
     * @covers Victoire\Bundle\MediaBundle\Entity\Folder::setCreatedAt
     */
    public function testGetSetCreatedAt()
    {
        $date = new \DateTime();
        $this->object->setCreatedAt($date);
        $this->assertEquals($date, $this->object->getCreatedAt());
    }

    /**
     * @covers Victoire\Bundle\MediaBundle\Entity\Folder::getUpdatedAt
     * @covers Victoire\Bundle\MediaBundle\Entity\Folder::setUpdatedAt
     */
    public function testGetSetUpdatedAt()
    {
        $date = new \DateTime();
        $this->object->setUpdatedAt($date);
        $this->assertEquals($date, $this->object->getUpdatedAt());
    }

    /**
     * @covers Victoire\Bundle\MediaBundle\Entity\Folder::getParent
     * @covers Victoire\Bundle\MediaBundle\Entity\Folder::setParent
     */
    public function testGetParent()
    {
        $parent = new Folder();
        $parent->setId(45);
        $this->object->setParent($parent);
        $this->assertEquals(45, $this->object->getParent()->getId());
    }

    /**
     * @covers Victoire\Bundle\MediaBundle\Entity\Folder::setDeleted
     * @covers Victoire\Bundle\MediaBundle\Entity\Folder::isDeleted
     */
    public function testSetDeleted()
    {
        $this->object->setDeleted(true);
        $this->assertEquals(true, $this->object->isDeleted());
        $this->object->setDeleted(false);
        $this->assertEquals(false, $this->object->isDeleted());
    }

}
