<?php

namespace Victoire\Bundle\AnalyticsBundle\Repository;

/**
 * BrowseEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrowseEventRepository extends \Doctrine\ORM\EntityRepository
{
}
