<?php

namespace Victoire\Bundle\FormBundle\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\ArrayNodeDefinition;
use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

/**
 * This is the class that validates and merges configuration from your app/config files
 *
 * To learn more see {@link http://symfony.com/doc/current/cookbook/bundles/extension.html#cookbook-bundles-extension-config-class}
 */
class Configuration implements ConfigurationInterface
{
    /**
     * {@inheritDoc}
     */
    public function getConfigTreeBuilder()
    {
        $treeBuilder = new TreeBuilder();
        $rootNode = $treeBuilder->root('victoire_form');
        $this->addFormConfig($rootNode);
        $this->addIconsConfig($rootNode);

        return $treeBuilder;
    }

    /**
     * Add form configuration
     * @param ArrayNodeDefinition $rootNode The root node
     */
    protected function addFormConfig(ArrayNodeDefinition $rootNode)
    {
        $rootNode
            ->children()
                ->arrayNode('form')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('templating')
                            ->defaultValue("VictoireFormBundle:Form:fields.html.twig")
                            ->end()
                        ->booleanNode('vic_horizontal')
                            ->defaultTrue()
                            ->end()
                        ->scalarNode('vic_horizontal_label_class')
                            ->defaultValue("")
                            ->end()
                        ->scalarNode('vic_horizontal_label_offset_class')
                            ->defaultValue("vic-col-lg-offset-3")
                            ->end()
                        ->scalarNode('vic_horizontal_input_wrapper_class')
                            ->defaultValue("")
                            ->end()
                        ->booleanNode('vic_render_fieldset')
                            ->defaultValue(true)
                            ->end()
                        ->booleanNode('vic_render_collection_item')
                            ->defaultValue(false)
                        ->end()
                        ->booleanNode('vic_show_legend')
                            ->defaultValue(true)
                            ->end()
                        ->booleanNode('vic_show_child_legend')
                            ->defaultValue(false)
                            ->end()
                        ->booleanNode('vic_legend_tag')
                            ->defaultValue('legend')
                            ->end()
                        ->scalarNode('vic_checkbox_label')
                            ->defaultValue('both')
                            ->end()
                        ->booleanNode('vic_render_optional_text')
                            ->defaultValue(true)
                            ->end()
                        ->booleanNode('vic_render_required_asterisk')
                            ->defaultValue(true)
                            ->end()
                        ->scalarNode('vic_error_type')
                            ->defaultValue(null)
                            ->end()
                        ->arrayNode('tabs')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->scalarNode('class')
                                    ->defaultValue('vic-nav vic-nav-tabs')
                                    ->end()
                            ->end()
                        ->end()
                        ->arrayNode('vic_help_widget')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->arrayNode('popover')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->scalarNode('title')
                                            ->defaultValue(null)
                                        ->end()
                                        ->scalarNode('content')
                                            ->defaultValue(null)
                                        ->end()
                                        ->scalarNode('trigger')
                                            ->defaultValue("hover")
                                        ->end()
                                        ->scalarNode('toggle')
                                            ->defaultValue("vic-popover")
                                        ->end()
                                        ->scalarNode('placement')
                                            ->defaultValue('right')
                                        ->end()
                                        ->scalarNode('selector')
                                            ->defaultValue(null)
                                        ->end()
                                    ->end()
                                ->end()
                            ->end()
                        ->end()
                        ->arrayNode('vic_help_label')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->arrayNode('tooltip')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->scalarNode('title')
                                            ->defaultValue(null)
                                        ->end()
                                        ->scalarNode('text')
                                            ->defaultValue(null)
                                        ->end()
                                        ->scalarNode('icon')
                                            ->defaultValue('vic-info-sign')
                                        ->end()
                                        ->scalarNode('placement')
                                            ->defaultValue('top')
                                        ->end()
                                    ->end()
                                ->end()
                                ->arrayNode('popover')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->scalarNode('title')
                                            ->defaultValue(null)
                                        ->end()
                                        ->scalarNode('content')
                                            ->defaultValue(null)
                                        ->end()
                                        ->scalarNode('text')
                                            ->defaultValue(null)
                                        ->end()
                                        ->scalarNode('icon')
                                            ->defaultValue('vic-info-sign')
                                            ->end()
                                        ->scalarNode('placement')
                                            ->defaultValue('top')
                                            ->end()
                                    ->end()
                                ->end()
                            ->end()
                        ->end()
                        ->arrayNode('collection')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->arrayNode('vic_widget_remove_btn')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->arrayNode('attr')
                                            ->addDefaultsIfNotSet()
                                            ->children()
                                                ->scalarNode('class')
                                                    ->defaultValue("btn btn-default")
                                                ->end()
                                            ->end()
                                        ->end()
                                        ->arrayNode('wrapper_div')
                                            ->addDefaultsIfNotSet()
                                            ->children()
                                                ->scalarNode('class')
                                                    ->defaultValue("vic-col-lg-3")
                                                ->end()
                                            ->end()
                                        ->end()
                                        ->scalarNode('label')
                                            ->defaultValue("victoire.collection.button.label.remove_item")
                                        ->end()
                                        ->scalarNode('icon')
                                            ->defaultValue(null)
                                        ->end()
                                        ->scalarNode('vic_icon_inverted')
                                            ->defaultValue(false)
                                        ->end()
                                    ->end()
                                 ->end()
                                ->arrayNode('vic_widget_add_btn')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->arrayNode('attr')
                                            ->addDefaultsIfNotSet()
                                            ->children()
                                                ->scalarNode('class')
                                                    ->defaultValue("vic-btn vic-btn-default")
                                                ->end()
                                            ->end()
                                        ->end()
                                        ->scalarNode('label')
                                            ->defaultValue("victoire.collection.button.label.add_item")
                                        ->end()
                                        ->scalarNode('icon')
                                            ->defaultValue(null)
                                        ->end()
                                        ->scalarNode('vic_icon_inverted')
                                            ->defaultValue(false)
                                        ->end()
                                    ->end()
                                 ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
            ->end();
    }

    /**
     * Add icon configuration
     * @param ArrayNodeDefinition $rootNode The root node
     */
    protected function addIconsConfig(ArrayNodeDefinition $rootNode)
    {
        $iconSets = array('glyphicons', 'fontawesome', 'fontawesome4');

        $rootNode
            ->children()
                ->arrayNode('icons')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('icon_set')
                            ->info('Icon set to use: '.json_encode($iconSets))
                            ->defaultValue('glyphicons')
                            ->validate()
                                ->ifNotInArray($iconSets)
                                ->thenInvalid('Must choose one of '.json_encode($iconSets))
                            ->end()
                        ->end()
                        ->scalarNode('shortcut')
                            ->info('Alias for vic_mopa_bootstrap_icon()')
                            ->defaultValue('icon')
                        ->end()
                    ->end()
                ->end()
            ->end();
    }
}
