services:
    victoire_form.error_helper:
        class: Victoire\Bundle\FormBundle\Helper\FormErrorHelper
        arguments:
            - "@translator"
            - "%kernel.debug%"

    victoire_form.form_type.urlvalidated_type:
        class: Victoire\Bundle\FormBundle\Form\Type\UrlvalidatedType
        arguments: ['@router']
        tags:
            - { name: form.type }
