install:
  build: .
  dockerfile: php-fpm/Dockerfile
  container_name: victoire-setup
  command: sh /var/www/victoire/.docker/php-fpm/build.sh
  links:
    - victoire-php
    - victoire-mailhog
    - victoire-mysql
    - victoire-redis
  volumes:
      - ..:/var/www/victoire
