behat:
  image: phpdocker_victoire-php-fpm
  restart: 'no'
  container_name: behat
  entrypoint: /var/www/victoire/vendor/bin/behat -c /var/www/victoire/.docker/php-fpm/behat.yml
  volumes:
    - ..:/var/www/victoire
  links:
    - victoire-setup
    - victoire-webserver
    - victoire-mailhog
    - victoire-mysql
    - victoire-redis
    - hub

hub:
  image: qualiboo/testing-hub
  ports:
    - 4444:4444
chrome:
  image: qualiboo/testing-node-chrome
  ports:
    - 5900
  environment:
    - no_proxy=localhost
    - HUB_ENV_no_proxy=localhost
  links:
    - hub
